### ISSUE TITLE
Build / publish wheels on Appveyor

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/initgroups#1]
Checklist from https://github.com/zopefoundation/zope.proxy/issues/24:

- [ ] a copy of `appveyor.yml` from `zope.interface` or similar
- [ ] someone with an Appveyor account (e.g. @mgedmin ) to enable this project
- [ ] encrypted PyPI upload credentials in the `appveyor.yml` (no change required from the copy in `zope.interface` if @mgedmin is the one who enables the Appveyor account)
- [ ] grant **zope.wheelbuilder** PyPI rights
- [ ] push the `appveyor.yml` commit to master
- [ ] (optionally) a push of a temporary branch that builds and uploads `initgroups 2.13.0` wheels

**Comment by icemac** [comment]
Zope 4 fixes this by using `os.initgroups` instead of this package. See https://github.com/zopefoundation/Zope/commit/05ecffc79f5b4d4a3e24fa89d2bc8bec516be479
Maybe this could be an alternative solution. (Even by replacing the C code in this package by pure Python.)

**Comment by tseaver** [comment]
@icemac Thanks for pointing that out.  I had missed that Python 2.7 added `os.initgroups`.  See #2.
